use_frameworks!

platform :ios, '10.0'

target 'GXAudioRecord_Example' do
  pod 'GXAudioRecord', :path => '../'
  pod 'Masonry'
  target 'GXAudioRecord_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
